apiVersion: v1
kind: Service
metadata:
  name: server-hub
spec:
  selector:
    app: server-hub
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 3000
    nodePort: 31000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-hub
spec:
  selector:
    matchLabels:
      app: server-hub
  replicas: 1
  template:
    metadata:
      labels:
        app: server-hub
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: server-hub
        image: server-hub-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000