apiVersion: v1
kind: Service
metadata:
  name: server-controller-sv
spec:
  selector:
    app: server-controller
  ports:
  - protocol: "TCP"
    port: 7000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-controller
spec:
  selector:
    matchLabels:
      app: server-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: server-controller
    spec:
      serviceAccountName: controller-k8s-api-sv
      containers:
      - name: server-controller
        image: server-controller:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000