# Create a ServiceAccount named "my-service-account" in the default namespace.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-k8s-api-sv

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-roles
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: [""]
  resources: ["services", "pods", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["create", "get", "list", "update", "delete"]

---

# Create a ClusterRoleBinding that associates the "view-pods" ClusterRole with the "controller-k8s-api-sv" ServiceAccount in the default namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-roles-binding
subjects:
- kind: ServiceAccount
  name: controller-k8s-api-sv
  namespace: default
roleRef:
  kind: ClusterRole
  name: service-roles
  apiGroup: rbac.authorization.k8s.io