apiVersion: v1
kind: Service
metadata:
  name: flask-server-api
spec:
  selector:
    app: flask-server-api
  ports:
  - protocol: "TCP"
    port: 7000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-server-api
spec:
  selector:
    matchLabels:
      app: flask-server-api
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-server-api
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: flask-server-api
        image: flask-server-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000