# Run mongo init script job
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:latest
        command: ["/bin/bash", "-c"]
        args:
          - "mongo --host server-templates-db-sv.default.svc.cluster.local:27017 --authenticationDatabase admin -u admin -p password minecraftServersDB < /init/mongo-init.js"
        volumeMounts:
        - name: mongo-init-script
          mountPath: /init
      restartPolicy: OnFailure
      volumes:
      - name: mongo-init-script
        configMap:
          name: server-templates-db-init-script
---