apiVersion: v1
kind: Service
metadata:
  name: server-templates-db-sv
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: server-templates-db
---
server-templates-db

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-templates-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server-templates-db
    spec:
      initContainers:
      - name: init-server-templates-db
        image: mongo:latest
        command: ['sh', '-c', 'mongo mongodb://admin:password@localhost:27017/minecraftServerDB /mongo-init.js']
        volumeMounts:
        - name: server-templates-db-init-volume
          mountPath: /mongo-init.js
          subPath: mongo-init.js
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: server-templates-db-data
          mountPath: /data/db
      volumes:
      - name: server-templates-db-data
        persistentVolumeClaim:
          claimName: server-templates-db-pvc
      - name: server-templates-db-init-volume
        configMap:
          name: server-templates-db-init-script