# DB Service
apiVersion: v1
kind: Service
metadata:
  name: server-templates-db-sv
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: server-templates-db
---

# DB deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-templates-db
spec:
  selector: 
    matchLabels:
      app: server-templates-db
  replicas: 1
  template:
    metadata:
      labels:
        app: server-templates-db
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        args: ["--dbpath","/data/db"]
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        volumeMounts:
        - name: server-templates-db-init-script
          mountPath: /docker-entrypoint-initdb.d
        - name: server-templates-db-data
          mountPath: /data/db
      volumes:
      - name: server-templates-db-init-script
        configMap:
          name: server-templates-db-init-script
      - name: server-templates-db-data
        persistentVolumeClaim:
          claimName: server-templates-db-pvc