apiVersion: v1
kind: Service
metadata:
  name: server-templates-api-sv
spec:
  # type: NodePort
  selector:
    app: server-templates-api
  ports:
  - protocol: "TCP"
    port: 31002
    targetPort: 5000
    # nodePort: 31002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-templates-api
spec:
  selector:
    matchLabels:
      app: server-templates-api
  replicas: 1
  template:
    metadata:
      labels:
        app: server-templates-api
    spec:
      containers:
      - name: server-templates-api
        image: server-templates-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000